name: ESLint
run-name: ${{ github.actor }} is executing ESLint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to the branch
        uses: actions/checkout@v3
      - name: exec eslint
        uses: reviewdog/action-eslint@v1
        run: yarn lint
