name: Rubocop
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  rubocop:
    name: exec
    runs-on: ubuntu-latest
    steps:
      - name: checkout to the branch
        uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
      - name: exec rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
